package com.muchu.heber.dao.model;

import java.util.Date;

public class ConsumeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_log.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_log.consume_time
     *
     * @mbggenerated
     */
    private Date consumeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_log.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_log.id
     *
     * @return the value of consume_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_log.id
     *
     * @param id the value for consume_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_log.user_id
     *
     * @return the value of consume_log.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_log.user_id
     *
     * @param userId the value for consume_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_log.consume_time
     *
     * @return the value of consume_log.consume_time
     *
     * @mbggenerated
     */
    public Date getConsumeTime() {
        return consumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_log.consume_time
     *
     * @param consumeTime the value for consume_log.consume_time
     *
     * @mbggenerated
     */
    public void setConsumeTime(Date consumeTime) {
        this.consumeTime = consumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_log.amount
     *
     * @return the value of consume_log.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_log.amount
     *
     * @param amount the value for consume_log.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }
}